# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created: Fri Jun 13 14:30:11 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(714, 711)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.imageWidget = ImageWidget(self.centralwidget)
        self.imageWidget.setGeometry(QtCore.QRect(10, 10, 640, 480))
        self.imageWidget.setOrientation(QtCore.Qt.Vertical)
        self.imageWidget.setObjectName(_fromUtf8("imageWidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 510, 189, 131))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.groupBox)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(10, 20, 169, 61))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label = QtGui.QLabel(self.formLayoutWidget_3)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.exposureTimeBox = QtGui.QSpinBox(self.formLayoutWidget_3)
        self.exposureTimeBox.setMinimum(1)
        self.exposureTimeBox.setMaximum(5000)
        self.exposureTimeBox.setSingleStep(10)
        self.exposureTimeBox.setProperty("value", 100)
        self.exposureTimeBox.setObjectName(_fromUtf8("exposureTimeBox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.exposureTimeBox)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.triggerModeBox = QtGui.QComboBox(self.formLayoutWidget_3)
        self.triggerModeBox.setObjectName(_fromUtf8("triggerModeBox"))
        self.triggerModeBox.addItem(_fromUtf8(""))
        self.triggerModeBox.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.triggerModeBox)
        self.acquisitionButton = QtGui.QPushButton(self.groupBox)
        self.acquisitionButton.setGeometry(QtCore.QRect(40, 90, 101, 23))
        self.acquisitionButton.setObjectName(_fromUtf8("acquisitionButton"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(450, 520, 231, 151))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 211, 111))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.scaleMinBox = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.scaleMinBox.setMaximum(9999)
        self.scaleMinBox.setSingleStep(20)
        self.scaleMinBox.setObjectName(_fromUtf8("scaleMinBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.scaleMinBox)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.scaleMaxBox = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.scaleMaxBox.setMinimum(1)
        self.scaleMaxBox.setMaximum(9999)
        self.scaleMaxBox.setSingleStep(10)
        self.scaleMaxBox.setProperty("value", 500)
        self.scaleMaxBox.setObjectName(_fromUtf8("scaleMaxBox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.scaleMaxBox)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.colormapBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.colormapBox.setObjectName(_fromUtf8("colormapBox"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.colormapBox)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.rbufferBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.rbufferBox.setEnabled(False)
        self.rbufferBox.setObjectName(_fromUtf8("rbufferBox"))
        self.verticalLayout.addWidget(self.rbufferBox)
        self.cropGroupBox = QtGui.QGroupBox(self.centralwidget)
        self.cropGroupBox.setGeometry(QtCore.QRect(220, 510, 221, 161))
        self.cropGroupBox.setObjectName(_fromUtf8("cropGroupBox"))
        self.gridLayoutWidget = QtGui.QWidget(self.cropGroupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 201, 126))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.yCropMinSlider = QtGui.QSlider(self.gridLayoutWidget)
        self.yCropMinSlider.setMinimum(1)
        self.yCropMinSlider.setOrientation(QtCore.Qt.Horizontal)
        self.yCropMinSlider.setObjectName(_fromUtf8("yCropMinSlider"))
        self.gridLayout.addWidget(self.yCropMinSlider, 2, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.xCropMaxSlider = QtGui.QSlider(self.gridLayoutWidget)
        self.xCropMaxSlider.setMinimum(2)
        self.xCropMaxSlider.setSliderPosition(99)
        self.xCropMaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.xCropMaxSlider.setObjectName(_fromUtf8("xCropMaxSlider"))
        self.gridLayout.addWidget(self.xCropMaxSlider, 1, 1, 1, 1)
        self.yCropMaxSlider = QtGui.QSlider(self.gridLayoutWidget)
        self.yCropMaxSlider.setMinimum(2)
        self.yCropMaxSlider.setSliderPosition(99)
        self.yCropMaxSlider.setOrientation(QtCore.Qt.Horizontal)
        self.yCropMaxSlider.setObjectName(_fromUtf8("yCropMaxSlider"))
        self.gridLayout.addWidget(self.yCropMaxSlider, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.xCropMinSlider = QtGui.QSlider(self.gridLayoutWidget)
        self.xCropMinSlider.setMinimum(1)
        self.xCropMinSlider.setOrientation(QtCore.Qt.Horizontal)
        self.xCropMinSlider.setObjectName(_fromUtf8("xCropMinSlider"))
        self.gridLayout.addWidget(self.xCropMinSlider, 0, 1, 1, 1)
        self.xCropMinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.xCropMinBox.setMinimum(1)
        self.xCropMinBox.setObjectName(_fromUtf8("xCropMinBox"))
        self.gridLayout.addWidget(self.xCropMinBox, 0, 2, 1, 1)
        self.xCropMaxBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.xCropMaxBox.setMinimum(2)
        self.xCropMaxBox.setProperty("value", 99)
        self.xCropMaxBox.setObjectName(_fromUtf8("xCropMaxBox"))
        self.gridLayout.addWidget(self.xCropMaxBox, 1, 2, 1, 1)
        self.yCropMinBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.yCropMinBox.setMinimum(1)
        self.yCropMinBox.setObjectName(_fromUtf8("yCropMinBox"))
        self.gridLayout.addWidget(self.yCropMinBox, 2, 2, 1, 1)
        self.yCropMaxBox = QtGui.QSpinBox(self.gridLayoutWidget)
        self.yCropMaxBox.setMinimum(2)
        self.yCropMaxBox.setProperty("value", 99)
        self.yCropMaxBox.setObjectName(_fromUtf8("yCropMaxBox"))
        self.gridLayout.addWidget(self.yCropMaxBox, 3, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.binsBox = QtGui.QComboBox(self.gridLayoutWidget)
        self.binsBox.setObjectName(_fromUtf8("binsBox"))
        self.binsBox.addItem(_fromUtf8(""))
        self.binsBox.addItem(_fromUtf8(""))
        self.binsBox.addItem(_fromUtf8(""))
        self.binsBox.addItem(_fromUtf8(""))
        self.binsBox.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.binsBox, 4, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 714, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.actionSave_image_as = QtGui.QAction(MainWindow)
        self.actionSave_image_as.setObjectName(_fromUtf8("actionSave_image_as"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionSave_image_as)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.xCropMaxSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.xCropMaxBox.setValue)
        QtCore.QObject.connect(self.xCropMinSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.xCropMinBox.setValue)
        QtCore.QObject.connect(self.yCropMinSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.yCropMinBox.setValue)
        QtCore.QObject.connect(self.yCropMaxSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.yCropMaxBox.setValue)
        QtCore.QObject.connect(self.xCropMinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.xCropMinSlider.setValue)
        QtCore.QObject.connect(self.xCropMaxBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.xCropMaxSlider.setValue)
        QtCore.QObject.connect(self.yCropMinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.yCropMinSlider.setValue)
        QtCore.QObject.connect(self.yCropMaxBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.yCropMaxSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "qCamera Viewer", None))
        self.groupBox.setTitle(_translate("MainWindow", "Exposure and Trigger", None))
        self.label.setText(_translate("MainWindow", "Exposure time [ms]", None))
        self.label_4.setText(_translate("MainWindow", "Trigger mode", None))
        self.triggerModeBox.setItemText(0, _translate("MainWindow", "software", None))
        self.triggerModeBox.setItemText(1, _translate("MainWindow", "external", None))
        self.acquisitionButton.setText(_translate("MainWindow", "Begin Acquisition", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Viewing Settings", None))
        self.label_2.setText(_translate("MainWindow", "Scale Min", None))
        self.label_3.setText(_translate("MainWindow", "Scale Max", None))
        self.label_5.setText(_translate("MainWindow", "Colormap", None))
        self.rbufferBox.setText(_translate("MainWindow", "Enable Ring Buffer", None))
        self.cropGroupBox.setTitle(_translate("MainWindow", "Crop and Bin Settings", None))
        self.label_8.setText(_translate("MainWindow", "y min", None))
        self.label_7.setText(_translate("MainWindow", "x max", None))
        self.label_6.setText(_translate("MainWindow", "x min", None))
        self.label_9.setText(_translate("MainWindow", "y max", None))
        self.label_10.setText(_translate("MainWindow", "Bins", None))
        self.binsBox.setItemText(0, _translate("MainWindow", "1", None))
        self.binsBox.setItemText(1, _translate("MainWindow", "2", None))
        self.binsBox.setItemText(2, _translate("MainWindow", "4", None))
        self.binsBox.setItemText(3, _translate("MainWindow", "8", None))
        self.binsBox.setItemText(4, _translate("MainWindow", "16", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionSave_image_as.setText(_translate("MainWindow", "Save image as...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))

from guiqwt.plot import ImageWidget
