# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'viewer.ui'
#
# Created: Mon Jun 23 16:14:46 2014
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(600, 889)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.tab)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 441, 83))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.exposureTimeBox = QtGui.QSpinBox(self.groupBox)
        self.exposureTimeBox.setMinimum(1)
        self.exposureTimeBox.setMaximum(5000)
        self.exposureTimeBox.setSingleStep(10)
        self.exposureTimeBox.setProperty("value", 100)
        self.exposureTimeBox.setObjectName(_fromUtf8("exposureTimeBox"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.exposureTimeBox)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_4)
        self.triggerModeBox = QtGui.QComboBox(self.groupBox)
        self.triggerModeBox.setObjectName(_fromUtf8("triggerModeBox"))
        self.triggerModeBox.addItem(_fromUtf8(""))
        self.triggerModeBox.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.triggerModeBox)
        self.verticalLayout_2.addLayout(self.formLayout_3)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.shutterGroupBox = QtGui.QGroupBox(self.horizontalLayoutWidget)
        self.shutterGroupBox.setObjectName(_fromUtf8("shutterGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.shutterGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.openShutterButton = QtGui.QRadioButton(self.shutterGroupBox)
        self.openShutterButton.setObjectName(_fromUtf8("openShutterButton"))
        self.horizontalLayout.addWidget(self.openShutterButton)
        self.closeShutterButton = QtGui.QRadioButton(self.shutterGroupBox)
        self.closeShutterButton.setChecked(True)
        self.closeShutterButton.setObjectName(_fromUtf8("closeShutterButton"))
        self.horizontalLayout.addWidget(self.closeShutterButton)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.shutterGroupBox)
        self.adjustCropButton = QtGui.QToolButton(self.horizontalLayoutWidget)
        self.adjustCropButton.setObjectName(_fromUtf8("adjustCropButton"))
        self.horizontalLayout_2.addWidget(self.adjustCropButton)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 100, 231, 151))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayoutWidget = QtGui.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 211, 111))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.scaleMinBox = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.scaleMinBox.setMaximum(9999)
        self.scaleMinBox.setSingleStep(20)
        self.scaleMinBox.setObjectName(_fromUtf8("scaleMinBox"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.scaleMinBox)
        self.label_3 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.scaleMaxBox = QtGui.QSpinBox(self.verticalLayoutWidget)
        self.scaleMaxBox.setMinimum(1)
        self.scaleMaxBox.setMaximum(9999)
        self.scaleMaxBox.setSingleStep(10)
        self.scaleMaxBox.setProperty("value", 2000)
        self.scaleMaxBox.setObjectName(_fromUtf8("scaleMaxBox"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.scaleMaxBox)
        self.label_5 = QtGui.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.colormapBox = QtGui.QComboBox(self.verticalLayoutWidget)
        self.colormapBox.setObjectName(_fromUtf8("colormapBox"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.colormapBox)
        self.verticalLayout.addLayout(self.formLayout_2)
        self.rbufferBox = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.rbufferBox.setEnabled(False)
        self.rbufferBox.setObjectName(_fromUtf8("rbufferBox"))
        self.verticalLayout.addWidget(self.rbufferBox)
        self.acquisitionButton = QtGui.QPushButton(self.tab)
        self.acquisitionButton.setGeometry(QtCore.QRect(300, 160, 101, 23))
        self.acquisitionButton.setObjectName(_fromUtf8("acquisitionButton"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 20, 113, 74))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.tempSetPointBox = QtGui.QSpinBox(self.groupBox_3)
        self.tempSetPointBox.setObjectName(_fromUtf8("tempSetPointBox"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.tempSetPointBox)
        self.label_10 = QtGui.QLabel(self.groupBox_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.groupBox_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.tempLbl = QtGui.QLabel(self.groupBox_3)
        self.tempLbl.setObjectName(_fromUtf8("tempLbl"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.tempLbl)
        self.verticalLayout_6.addLayout(self.formLayout_5)
        self.coolerStateBox = QtGui.QGroupBox(self.tab_3)
        self.coolerStateBox.setGeometry(QtCore.QRect(20, 100, 102, 50))
        self.coolerStateBox.setObjectName(_fromUtf8("coolerStateBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.coolerStateBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.coolerOnButton = QtGui.QRadioButton(self.coolerStateBox)
        self.coolerOnButton.setObjectName(_fromUtf8("coolerOnButton"))
        self.horizontalLayout_3.addWidget(self.coolerOnButton)
        self.coolerOffButton = QtGui.QRadioButton(self.coolerStateBox)
        self.coolerOffButton.setChecked(True)
        self.coolerOffButton.setObjectName(_fromUtf8("coolerOffButton"))
        self.horizontalLayout_3.addWidget(self.coolerOffButton)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.roiHistWidget = CurveWidget(self.groupBox_5)
        self.roiHistWidget.setOrientation(QtCore.Qt.Horizontal)
        self.roiHistWidget.setObjectName(_fromUtf8("roiHistWidget"))
        self.verticalLayout_3.addWidget(self.roiHistWidget)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.xHistLimBox = QtGui.QSpinBox(self.groupBox_5)
        self.xHistLimBox.setMaximum(65536)
        self.xHistLimBox.setSingleStep(100)
        self.xHistLimBox.setProperty("value", 500)
        self.xHistLimBox.setObjectName(_fromUtf8("xHistLimBox"))
        self.gridLayout_3.addWidget(self.xHistLimBox, 0, 1, 1, 1)
        self.yHistLimBox = QtGui.QSpinBox(self.groupBox_5)
        self.yHistLimBox.setMaximum(65536)
        self.yHistLimBox.setSingleStep(10)
        self.yHistLimBox.setProperty("value", 2000)
        self.yHistLimBox.setObjectName(_fromUtf8("yHistLimBox"))
        self.gridLayout_3.addWidget(self.yHistLimBox, 0, 3, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox_5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_3.addWidget(self.label_20, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.gridLayout_2.addWidget(self.groupBox_5, 0, 0, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.showROIBox = QtGui.QCheckBox(self.groupBox_4)
        self.showROIBox.setEnabled(False)
        self.showROIBox.setObjectName(_fromUtf8("showROIBox"))
        self.gridLayout.addWidget(self.showROIBox, 1, 0, 1, 1)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_15)
        self.roiTotalLbl = QtGui.QLabel(self.groupBox_4)
        self.roiTotalLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roiTotalLbl.setObjectName(_fromUtf8("roiTotalLbl"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.roiTotalLbl)
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_16)
        self.roiMeanLbl = QtGui.QLabel(self.groupBox_4)
        self.roiMeanLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roiMeanLbl.setObjectName(_fromUtf8("roiMeanLbl"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.roiMeanLbl)
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_17)
        self.roiMinLbl = QtGui.QLabel(self.groupBox_4)
        self.roiMinLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roiMinLbl.setObjectName(_fromUtf8("roiMinLbl"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.roiMinLbl)
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_18)
        self.roiMaxLbl = QtGui.QLabel(self.groupBox_4)
        self.roiMaxLbl.setEnabled(True)
        self.roiMaxLbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roiMaxLbl.setObjectName(_fromUtf8("roiMaxLbl"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.roiMaxLbl)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 1)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_9)
        self.roiX1Lbl = QtGui.QLabel(self.groupBox_4)
        self.roiX1Lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roiX1Lbl.setObjectName(_fromUtf8("roiX1Lbl"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.roiX1Lbl)
        self.roiX2Lbl = QtGui.QLabel(self.groupBox_4)
        self.roiX2Lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roiX2Lbl.setObjectName(_fromUtf8("roiX2Lbl"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.roiX2Lbl)
        self.roiY1Lbl = QtGui.QLabel(self.groupBox_4)
        self.roiY1Lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roiY1Lbl.setObjectName(_fromUtf8("roiY1Lbl"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.roiY1Lbl)
        self.roiY2Lbl = QtGui.QLabel(self.groupBox_4)
        self.roiY2Lbl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.roiY2Lbl.setObjectName(_fromUtf8("roiY2Lbl"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.roiY2Lbl)
        self.gridLayout.addLayout(self.formLayout_4, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 1, 0, 1, 1)
        self.adjustROIButton = QtGui.QToolButton(self.tab_2)
        self.adjustROIButton.setObjectName(_fromUtf8("adjustROIButton"))
        self.gridLayout_2.addWidget(self.adjustROIButton, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuRing_Buffer = QtGui.QMenu(self.menubar)
        self.menuRing_Buffer.setObjectName(_fromUtf8("menuRing_Buffer"))
        MainWindow.setMenuBar(self.menubar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.imageWidget = ImageWidget(self.dockWidgetContents)
        self.imageWidget.setOrientation(QtCore.Qt.Vertical)
        self.imageWidget.setObjectName(_fromUtf8("imageWidget"))
        self.verticalLayout_4.addWidget(self.imageWidget)
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget)
        self.actionSave_image_as = QtGui.QAction(MainWindow)
        self.actionSave_image_as.setObjectName(_fromUtf8("actionSave_image_as"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionEnable = QtGui.QAction(MainWindow)
        self.actionEnable.setCheckable(True)
        self.actionEnable.setChecked(False)
        self.actionEnable.setObjectName(_fromUtf8("actionEnable"))
        self.actionView = QtGui.QAction(MainWindow)
        self.actionView.setObjectName(_fromUtf8("actionView"))
        self.menuFile.addAction(self.actionSave_image_as)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout)
        self.menuRing_Buffer.addAction(self.actionEnable)
        self.menuRing_Buffer.addAction(self.actionView)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRing_Buffer.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.scaleMinBox, self.scaleMaxBox)
        MainWindow.setTabOrder(self.scaleMaxBox, self.xHistLimBox)
        MainWindow.setTabOrder(self.xHistLimBox, self.yHistLimBox)
        MainWindow.setTabOrder(self.yHistLimBox, self.triggerModeBox)
        MainWindow.setTabOrder(self.triggerModeBox, self.colormapBox)
        MainWindow.setTabOrder(self.colormapBox, self.rbufferBox)
        MainWindow.setTabOrder(self.rbufferBox, self.acquisitionButton)
        MainWindow.setTabOrder(self.acquisitionButton, self.exposureTimeBox)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "qCamera Viewer", None))
        self.groupBox.setTitle(_translate("MainWindow", "Exposure and Trigger Settings", None))
        self.label.setText(_translate("MainWindow", "Exposure time [ms]", None))
        self.label_4.setText(_translate("MainWindow", "Trigger mode", None))
        self.triggerModeBox.setItemText(0, _translate("MainWindow", "software", None))
        self.triggerModeBox.setItemText(1, _translate("MainWindow", "external", None))
        self.shutterGroupBox.setTitle(_translate("MainWindow", "Shutter", None))
        self.openShutterButton.setText(_translate("MainWindow", "Open", None))
        self.closeShutterButton.setText(_translate("MainWindow", "Closed", None))
        self.adjustCropButton.setText(_translate("MainWindow", "Adjust Crop", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Viewing Settings", None))
        self.label_2.setText(_translate("MainWindow", "Scale Min", None))
        self.label_3.setText(_translate("MainWindow", "Scale Max", None))
        self.label_5.setText(_translate("MainWindow", "Colormap", None))
        self.rbufferBox.setText(_translate("MainWindow", "Enable Ring Buffer", None))
        self.acquisitionButton.setText(_translate("MainWindow", "Begin Acquisition", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Acquisition", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Temperature Settings", None))
        self.label_10.setText(_translate("MainWindow", "Set Point", None))
        self.label_11.setText(_translate("MainWindow", "Actual", None))
        self.tempLbl.setText(_translate("MainWindow", "20", None))
        self.coolerStateBox.setTitle(_translate("MainWindow", "Cooler State", None))
        self.coolerOnButton.setText(_translate("MainWindow", "On", None))
        self.coolerOffButton.setText(_translate("MainWindow", "Off", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Gain/Temperature", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "ROI Histogram", None))
        self.label_19.setText(_translate("MainWindow", "x lim", None))
        self.label_20.setText(_translate("MainWindow", "y lim", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "ROI Statistics", None))
        self.showROIBox.setText(_translate("MainWindow", "Show ROI", None))
        self.label_15.setText(_translate("MainWindow", "Total", None))
        self.roiTotalLbl.setText(_translate("MainWindow", "0", None))
        self.label_16.setText(_translate("MainWindow", "Mean", None))
        self.roiMeanLbl.setText(_translate("MainWindow", "0", None))
        self.label_17.setText(_translate("MainWindow", "Min", None))
        self.roiMinLbl.setText(_translate("MainWindow", "0", None))
        self.label_18.setText(_translate("MainWindow", "Max", None))
        self.roiMaxLbl.setText(_translate("MainWindow", "0", None))
        self.label_6.setText(_translate("MainWindow", "x1", None))
        self.label_7.setText(_translate("MainWindow", "x2", None))
        self.label_8.setText(_translate("MainWindow", "y1", None))
        self.label_9.setText(_translate("MainWindow", "y2", None))
        self.roiX1Lbl.setText(_translate("MainWindow", "1", None))
        self.roiX2Lbl.setText(_translate("MainWindow", "2", None))
        self.roiY1Lbl.setText(_translate("MainWindow", "1", None))
        self.roiY2Lbl.setText(_translate("MainWindow", "2", None))
        self.adjustROIButton.setText(_translate("MainWindow", "Adjust ROI", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "ROI", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuRing_Buffer.setTitle(_translate("MainWindow", "Ring Buffer", None))
        self.actionSave_image_as.setText(_translate("MainWindow", "Save image as...", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionEnable.setText(_translate("MainWindow", "Enable", None))
        self.actionView.setText(_translate("MainWindow", "View", None))

from guiqwt.plot import CurveWidget, ImageWidget
