# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'setup_dialog.ui'
#
# Created: Thu Aug  7 10:28:17 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_SetupDialog(object):
    def setupUi(self, SetupDialog):
        SetupDialog.setObjectName(_fromUtf8("SetupDialog"))
        SetupDialog.setWindowModality(QtCore.Qt.WindowModal)
        SetupDialog.resize(298, 538)
        self.verticalLayout_3 = QtGui.QVBoxLayout(SetupDialog)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.acquisitionGroupBox = QtGui.QGroupBox(SetupDialog)
        self.acquisitionGroupBox.setObjectName(_fromUtf8("acquisitionGroupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.acquisitionGroupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.acquisitionGroupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.binsBox = QtGui.QComboBox(self.acquisitionGroupBox)
        self.binsBox.setObjectName(_fromUtf8("binsBox"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.binsBox)
        self.label_4 = QtGui.QLabel(self.acquisitionGroupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_4)
        self.triggerModeBox = QtGui.QComboBox(self.acquisitionGroupBox)
        self.triggerModeBox.setObjectName(_fromUtf8("triggerModeBox"))
        self.triggerModeBox.addItem(_fromUtf8(""))
        self.triggerModeBox.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.triggerModeBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.adjustCropButton_2 = QtGui.QPushButton(self.acquisitionGroupBox)
        self.adjustCropButton_2.setEnabled(False)
        self.adjustCropButton_2.setObjectName(_fromUtf8("adjustCropButton_2"))
        self.verticalLayout.addWidget(self.adjustCropButton_2)
        self.shutterGroupBox = QtGui.QGroupBox(self.acquisitionGroupBox)
        self.shutterGroupBox.setObjectName(_fromUtf8("shutterGroupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.shutterGroupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.openShutterButton = QtGui.QRadioButton(self.shutterGroupBox)
        self.openShutterButton.setChecked(True)
        self.openShutterButton.setObjectName(_fromUtf8("openShutterButton"))
        self.horizontalLayout.addWidget(self.openShutterButton)
        self.closeShutterButton = QtGui.QRadioButton(self.shutterGroupBox)
        self.closeShutterButton.setChecked(False)
        self.closeShutterButton.setObjectName(_fromUtf8("closeShutterButton"))
        self.horizontalLayout.addWidget(self.closeShutterButton)
        self.verticalLayout.addWidget(self.shutterGroupBox)
        self.verticalLayout_3.addWidget(self.acquisitionGroupBox)
        self.gainGroupBox = QtGui.QGroupBox(SetupDialog)
        self.gainGroupBox.setObjectName(_fromUtf8("gainGroupBox"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.gainGroupBox)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.gainSlider = QtGui.QSlider(self.gainGroupBox)
        self.gainSlider.setOrientation(QtCore.Qt.Horizontal)
        self.gainSlider.setObjectName(_fromUtf8("gainSlider"))
        self.horizontalLayout_6.addWidget(self.gainSlider)
        self.gainLbl = QtGui.QLabel(self.gainGroupBox)
        self.gainLbl.setObjectName(_fromUtf8("gainLbl"))
        self.horizontalLayout_6.addWidget(self.gainLbl)
        self.verticalLayout_3.addWidget(self.gainGroupBox)
        self.tempGroupBox = QtGui.QGroupBox(SetupDialog)
        self.tempGroupBox.setObjectName(_fromUtf8("tempGroupBox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tempGroupBox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.tempSetPointBox = QtGui.QSpinBox(self.tempGroupBox)
        self.tempSetPointBox.setObjectName(_fromUtf8("tempSetPointBox"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.tempSetPointBox)
        self.label_10 = QtGui.QLabel(self.tempGroupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtGui.QLabel(self.tempGroupBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_11)
        self.tempLbl = QtGui.QLabel(self.tempGroupBox)
        self.tempLbl.setObjectName(_fromUtf8("tempLbl"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.FieldRole, self.tempLbl)
        self.verticalLayout_2.addLayout(self.formLayout_5)
        self.coolerStateBox = QtGui.QGroupBox(self.tempGroupBox)
        self.coolerStateBox.setObjectName(_fromUtf8("coolerStateBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.coolerStateBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.coolerOnButton = QtGui.QRadioButton(self.coolerStateBox)
        self.coolerOnButton.setObjectName(_fromUtf8("coolerOnButton"))
        self.horizontalLayout_3.addWidget(self.coolerOnButton)
        self.coolerOffButton = QtGui.QRadioButton(self.coolerStateBox)
        self.coolerOffButton.setChecked(True)
        self.coolerOffButton.setObjectName(_fromUtf8("coolerOffButton"))
        self.horizontalLayout_3.addWidget(self.coolerOffButton)
        self.verticalLayout_2.addWidget(self.coolerStateBox)
        self.verticalLayout_3.addWidget(self.tempGroupBox)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.closeButton = QtGui.QPushButton(SetupDialog)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout_4.addWidget(self.closeButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.retranslateUi(SetupDialog)
        QtCore.QMetaObject.connectSlotsByName(SetupDialog)

    def retranslateUi(self, SetupDialog):
        SetupDialog.setWindowTitle(QtGui.QApplication.translate("SetupDialog", "Camera Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.acquisitionGroupBox.setTitle(QtGui.QApplication.translate("SetupDialog", "Acquisition", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("SetupDialog", "Bins", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("SetupDialog", "Trigger mode", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerModeBox.setItemText(0, QtGui.QApplication.translate("SetupDialog", "software", None, QtGui.QApplication.UnicodeUTF8))
        self.triggerModeBox.setItemText(1, QtGui.QApplication.translate("SetupDialog", "external", None, QtGui.QApplication.UnicodeUTF8))
        self.adjustCropButton_2.setText(QtGui.QApplication.translate("SetupDialog", "Adjust Crop", None, QtGui.QApplication.UnicodeUTF8))
        self.shutterGroupBox.setTitle(QtGui.QApplication.translate("SetupDialog", "Shutter", None, QtGui.QApplication.UnicodeUTF8))
        self.openShutterButton.setText(QtGui.QApplication.translate("SetupDialog", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.closeShutterButton.setText(QtGui.QApplication.translate("SetupDialog", "Closed", None, QtGui.QApplication.UnicodeUTF8))
        self.gainGroupBox.setTitle(QtGui.QApplication.translate("SetupDialog", "Gain", None, QtGui.QApplication.UnicodeUTF8))
        self.gainLbl.setText(QtGui.QApplication.translate("SetupDialog", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.tempGroupBox.setTitle(QtGui.QApplication.translate("SetupDialog", "Temperature", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("SetupDialog", "Set Point", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("SetupDialog", "Actual", None, QtGui.QApplication.UnicodeUTF8))
        self.tempLbl.setText(QtGui.QApplication.translate("SetupDialog", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.coolerStateBox.setTitle(QtGui.QApplication.translate("SetupDialog", "Cooler State", None, QtGui.QApplication.UnicodeUTF8))
        self.coolerOnButton.setText(QtGui.QApplication.translate("SetupDialog", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.coolerOffButton.setText(QtGui.QApplication.translate("SetupDialog", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("SetupDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

